### ISSUE TITLE
Fatal error: Cannot redeclare open_form()

### ISSUE THREAD

**Issue by optimizamx** [damanic/ls1-module-cms#1]
Fatal error: Cannot redeclare open_form() (previously declared in ...../modules/cms/init/custom_helpers.php:28) in ....../modules/ls1-module-cms/init/custom_helpers.php on line 41

**Comment by EHLOVader** [comment]
From my understanding of this, it is meant to replace the contents of your the core CMS. Not to be installed alongside the other. 

Have you removed the CMS folder from the core? You will also need to turn off updates from LemonStand.
