### ISSUE TITLE
Integration settings keep switching to 'off' after save.

### ISSUE THREAD

**Issue by Flynsarmy** [damanic/ls1-module-cms#5]
I turned on 'Enable Google Analytics integration' and entered my View ID and JSON file, hit save, then went back into statistics and the checkbox was switched off again.

**Comment by damanic** [comment]
First thought, sql updates. Did you trigger them with log out/in before setting the switch?

**Comment by Flynsarmy** [comment]
My bad. I've been manually copying your commits into my files and stupidly missed the SQL changes. THanks.
